package com.ruoyi.common.web.rsql;

public enum TokenType {
    UnknownToken,
    IntegerToken,
    DoubleToken,
    DateToken,
    DateTimeToken,
    BooleanToken,
    IdentifierToken,
    StringToken,
    LeftParenToken,
    RightParenToken,
    OrToken,
    AndToken,
    ContainsToken,
    NotContainsToken,
    IsNullToken,
    NotIsNullToken,
    EqualsToken,
    NotEqualsToken,
    LikeToken,
    NotLikeToken,
    GreaterToken,
    GreaterOrEqualsToken,
    LessToken,
    LessOrEqualsToken,
    InToken,
    NotInToken,
    CommaToken,
    StartToken,
    EndToken,
    EOFToken,
    FuncToken
}